---
title: C28105 | Microsoft Docs
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology: vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords: C28105
helpviewer_keywords: C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: "3"
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: ca95eb9c1dab23d934bccb2a765127ed9d1e5aa6
ms.sourcegitcommit: fb751e41929f031d1a9247bc7c8727312539ad35
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 11/15/2017
---
# <a name="c28105"></a>C28105
Warnung C28105: Speicherverlust Ressource aufgrund einer Ausnahme  
  
 Die angegebene Ressource ist nicht freigegeben, wenn eine Ausnahme ausgelöst wird. Die Anweisung, die vom Pfad angegebenen kann eine Ausnahme ausgelöst. Diese Warnung ist ähnlich wie in "Warnung" [C28103](../code-quality/c28103.md), außer dass in diesem Fall eine Ausnahme beteiligt ist.  
  
## <a name="example"></a>Beispiel  
 Im folgenden Codebeispiel wird diese Warnung generiert:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 Im folgenden Codebeispiel wird diese Warnung vermieden:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```