---
title: "C28105 | Microsoft Docs"
ms.custom: ""
ms.date: "11/04/2016"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C28105"
helpviewer_keywords: 
  - "C28105"
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 3
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
caps.handback.revision: 3
---
# C28105
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

Warnung C28105: Verlust von Ressource aufgrund einer Ausnahme  
  
 Die angegebene Ressource wird nicht freigegeben, wenn eine Ausnahme ausgelöst wird.  Die Anweisung, die durch den Pfad angegeben ist, kann eine Ausnahme auslösen.  Diese Warnung wird z Warnung von [C28103](../code-quality/c28103.md) ähnlich, außer dass in diesem Fall wird eine Ausnahme beteiligt.  
  
## Beispiel  
 Im folgenden Code wird diese Warnung generiert:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 Im folgenden Codebeispiel werden diese Warnung:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```