---
title: C6310
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6310
helpviewer_keywords:
- C6310
ms.assetid: e759eb63-883f-4c3e-bf2f-b924ff511405
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 3b7d3c82ed40f270c9bbe83ba0a0408d50dddcc1
ms.sourcegitcommit: 240c8b34e80952d00e90c52dcb1a077b9aff47f6
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 10/23/2018
ms.locfileid: "49837372"
---
# <a name="c6310"></a>C6310
Warnung C6310: Eine unzul채ssige Konstante im Ausnahmefilter kann unerwartetes Verhalten verursachen.

Diese Meldung gibt an, dass eine unzul채ssige Konstante im Filterausdruck eine strukturierte Ausnahmehandler erkannt wurde. Die Konstanten, die f체r die Verwendung in einem strukturierten Ausnahmehandler Filterausdruck definiert sind:

- `EXCEPTION_CONTINUE_EXECUTION`

- `EXCEPTION_CONTINUE_SEARCH`

- `EXCEPTION_EXECUTE_HANDLER`

Diese Werte werden in der Common Language Runtime-Header-Datei excpt.h definiert.

Verwenden eine Konstante, die nicht in der vorangehenden Liste aufgef체hrt ist, kann unerwartetes Verhalten verursachen.

## <a name="example"></a>Beispiel

Der folgende Code generiert diese Warnung:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

BOOL LimitExceeded();

void fd( )
{
  __try
  {
    if (LimitExceeded())
    {
      RaiseException(EXCEPTION_ACCESS_VIOLATION,0,0,0);
    }
    else
    {
      // code
    }
  }
  __except (EXCEPTION_ACCESS_VIOLATION)
  {
    puts("Exception Occurred");
  }
}
```

So korrigieren Sie die Warnung unter Verwendung des folgenden Codes

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

BOOL LimitExceeded();

void fd( )
{
  __try
  {
    if (LimitExceeded())
    {
      RaiseException(EXCEPTION_ACCESS_VIOLATION,0,0,0);
    }
    else
    {
      // code
    }
  }
  __except (GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Exception Occurred");
  }
}
```