---
title: C6320 | Microsoft Docs
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology: vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords: C6320
helpviewer_keywords: C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: "10"
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload: multiple
ms.openlocfilehash: dbf498f943fb4f6e446cd254e7ca5f844ee0ec68
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 12/22/2017
---
# <a name="c6320"></a>C6320
Warnung C6320: Der Ausnahmefilterausdruck ist die EXCEPTION_EXECUTE_HANDLER-Konstante. Hierdurch werden möglicherweise Ausnahmen maskiert, für die keine Behandlung vorgesehen war.  
  
 Diese Warnung gibt an, den Nebeneffekt der Verwendung von EXCEPTION_EXECUTE_HANDLER-Konstante im __except-Block. In diesem Fall wird die Anweisung in der \__except-Block wird immer ausgeführt, um die Ausnahme, einschließlich Ausnahmen, die Sie nicht in einer bestimmten Funktion behandeln möchten. Es wird empfohlen, dass die Ausnahme vor der Behandlung zu überprüfen.  
  
## <a name="example"></a>Beispiel  
 Der folgende Code generiert diese Warnung, weil der __except-block Behandeln von Ausnahmen aller Typen versuchen:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Um diese Warnung zu korrigieren, verwenden `GetExceptionCode` , überprüfen Sie für eine bestimmte Ausnahme vor der Behandlung wie im folgenden Code gezeigt:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Siehe auch  
 [try-except-Anweisung](/cpp/cpp/try-except-statement)