---
title: "C6322 | Microsoft Docs"
ms.custom: ""
ms.date: "12/02/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C6322"
helpviewer_keywords: 
  - "C6322"
ms.assetid: fb23d2b1-b2a0-465c-8bf5-ec039c6c7757
caps.latest.revision: 13
caps.handback.revision: 13
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
---
# C6322
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

Warnung C6322: leerer \_except\-Block  
  
 Diese Meldung gibt an, dass der \_except\-Block keinen Code enthält.  Aus diesem Grund werden Ausnahmen möglicherweise nicht behandelt.  
  
## Beispiel  
 Der folgende Code generiert diese Warnung:  
  
```  
#include <stdio.h>  
#include <excpt.h>  
#include <windows.h>  
  
void fd(char *pch)  
{  
   __try  
     {  
       // exception rasied if pch is null  
       *pch= 0 ;  
     }  
   __except(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION)  
     {  
     }  
}  
```  
  
 So korrigieren Sie die Warnung unter Verwendung des folgenden Codes  
  
```  
#include <stdio.h>  
#include <excpt.h>  
#include <windows.h>  
  
void f(char *pch)  
{  
   __try  
     {  
       // exception rasied if pch is null  
      *pch= 0 ;  
     }  
   __except(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
     {  
       // code to handle exception  
       puts("Exception Occurred");     
     }  
}    
```  
  
## Siehe auch  
 [try\-except\-Anweisung](/visual-cpp/cpp/try-except-statement)